Conserve gpu memory by storing history on cpu memory instead
This patch offloads AADL history to the cpu memory instead of using valuable gpu memory.

This incurs a performance hit of transferring the vectors to and from cpu memory, but allows
for training with a smaller reduction in batch size than without the patch and not run out of memory.
  - This can probably be ameliorated by interleaving the memory transfers with the computation.

This change also fixes a bug with `torch.nn.utils.convert_parameters.vector_to_parameters` where
it does not preserve the `memory_format` of `param.data`.

History device offload is configurable by the user so that they can continue to use gpu memory for history
if they prefer that for some reason instead (by using `accelerate(..., history_device="cuda")`.

For reference, I get errors like this without cpu memory offload:
```
RuntimeError: CUDA out of memory. Tried to allocate 2.55 GiB (GPU 0; 24.00 GiB total capacity; 16.60 GiB already allocated; 1.82 GiB free; 19.75 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```